version: '3.8'

services:
  # notebook:
  #   build: .
  #   ports:
  #     - "8888:8888"
  #   volumes:
  #     - .:/app
  #   environment:
  #     - JUPYTER_TOKEN=taxi

  # data:
  #   build: 
  #     context: ./data
  #     dockerfile: Dockerfile
  #   volumes:
  #     - .:/app
  #   working_dir: /app
  #   command: ["python", "data/download_data.py", "--years", "2022,2023,2024"]

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - taxi-network

  model:
    build:
      context: ./model
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - taxi-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - model
    networks:
      - taxi-network

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    volumes:
      - ./src/frontend:/app
      - ./.streamlit:/app/.streamlit
    depends_on:
      - api
    networks:
      - taxi-network

networks:
  taxi-network:
    driver: bridge


  # volumes:
  #   nyc_taxi_data:
  #     name: nyc_taxi_data 